# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azure_service_connection: 'ansiblekey'  # Replace with the name of your service connection

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install ansible[azure]
  displayName: 'Install Ansible'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azure_service_connection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      ansible-playbook create_resources.yml
  env:
    AZURE_CLIENT_ID: $(servicePrincipalId)
    AZURE_SECRET: $(servicePrincipalKey)
    AZURE_SUBSCRIPTION_ID: $(subscriptionId)
    AZURE_TENANT: $(tenantId)
